-- MySQL Script generated by MySQL Workbench
-- mar 31 may 2022 14:13:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airSystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `airSystem` ;

-- -----------------------------------------------------
-- Schema airSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airSystem` ;
USE `airSystem` ;

-- -----------------------------------------------------
-- Table `airSystem`.`devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airSystem`.`devices` ;

CREATE TABLE IF NOT EXISTS `airSystem`.`devices` (
  `idDevice` INT NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idDevice`),
  UNIQUE INDEX `idBoard_UNIQUE` (`idDevice` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `airSystem`.`sensors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airSystem`.`sensors` ;

CREATE TABLE IF NOT EXISTS `airSystem`.`sensors` (
  `idSensor` INT NOT NULL,
  `idDevice` INT NOT NULL,
  PRIMARY KEY (`idSensor`),
  UNIQUE INDEX `idBoard_UNIQUE` (`idSensor` ASC) VISIBLE,
  INDEX `fk_sensors_devices1_idx` (`idDevice` ASC) VISIBLE,
  CONSTRAINT `fk_sensors_devices1`
    FOREIGN KEY (`idDevice`)
    REFERENCES `airSystem`.`devices` (`idDevice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `airSystem`.`actuators`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airSystem`.`actuators` ;

CREATE TABLE IF NOT EXISTS `airSystem`.`actuators` (
  `idActuator` INT NOT NULL,
  `mode` VARCHAR(6) NOT NULL,
  `idDevice` INT NOT NULL,
  PRIMARY KEY (`idActuator`),
  UNIQUE INDEX `idBoard_UNIQUE` (`idActuator` ASC) VISIBLE,
  INDEX `fk_actuators_devices1_idx` (`idDevice` ASC) VISIBLE,
  CONSTRAINT `fk_actuators_devices1`
    FOREIGN KEY (`idDevice`)
    REFERENCES `airSystem`.`devices` (`idDevice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `airSystem`.`sensorValues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airSystem`.`sensorValues` ;

CREATE TABLE IF NOT EXISTS `airSystem`.`sensorValues` (
  `idSensorValue` INT NOT NULL AUTO_INCREMENT,
  `temp` DOUBLE NOT NULL,
  `hum` DOUBLE NOT NULL,
  `time` BIGINT NOT NULL,
  `idSensor` INT NOT NULL,
  PRIMARY KEY (`idSensorValue`),
  UNIQUE INDEX `idSensorValues_UNIQUE` (`idSensorValue` ASC) VISIBLE,
  INDEX `fk_sensorValues_sensors1_idx` (`idSensor` ASC) VISIBLE,
  CONSTRAINT `fk_sensorValues_sensors1`
    FOREIGN KEY (`idSensor`)
    REFERENCES `airSystem`.`sensors` (`idSensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `airSystem`.`actuatorValues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airSystem`.`actuatorValues` ;

CREATE TABLE IF NOT EXISTS `airSystem`.`actuatorValues` (
  `idActuatorValue` INT NOT NULL AUTO_INCREMENT,
  `value` DOUBLE(4,2) NOT NULL,
  `idActuator` INT NOT NULL,
  PRIMARY KEY (`idActuatorValue`),
  UNIQUE INDEX `idActuatosValues_UNIQUE` (`idActuatorValue` ASC) VISIBLE,
  CONSTRAINT `fk_actuatorValues_actuators1`
    FOREIGN KEY (`idActuator`)
    REFERENCES `airSystem`.`actuators` (`idActuator`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
